## Installation Instructions

conda install numpy

pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by arrays....


# Numpy Arrays

Numpy arrays essentially come in two way: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

The most important object defined in NumPy is an N-dimensional array type called ndarray. 

In [13]:
# 2D array
arr=np.array(my_matrix)

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

###  The more important attributes of an ndarray object are:

In [14]:
arr.shape

(3, 3)

In [15]:
arr.ndim

2

In [16]:
arr.size

9

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr.itemsize

4

In [20]:
arr.data

In [21]:
type(arr)

numpy.ndarray

In [87]:
# minimum dimensions  
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [6]:
# create ndarray from tuple 
x = (1,2,3) 
a = np.array(x) 
a

array([1, 2, 3])

## Data Type

NumPy supports a much greater variety of numerical types than Python does. 

Like --bool_,int_,intc,intp,int8,int16,int32,int64,uint8,float_,float16,float32,float64,complex_,complex16,complex32,complex64,complex128

In [86]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [88]:
# using array-scalar type 
dt = np.dtype(np.int32) 
print (dt)

int32


In [90]:
# dt = np.dtype([('age',np.int8)]) 
# print(dt) 

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [28]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [97]:
# find retstep value 

x = np.linspace(1,2,5, retstep = True) 
print (x) 
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


### eye
Creates an identity matrix

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Empty 

In [32]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
# np.empty(shape, dtype = float, order = 'C')
np.empty([3,2], dtype = int, order = 'C')

array([[         0, 1072693248],
       [         0, 1073741824],
       [         0, 1074266112]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [34]:
np.random.rand(2)

array([0.9885681 , 0.19861592])

In [35]:
np.random.rand(5,5)

array([[0.95121222, 0.44178313, 0.5466446 , 0.23588665, 0.75257422],
       [0.46922504, 0.93496346, 0.32787009, 0.15672692, 0.20656326],
       [0.50249203, 0.08479081, 0.34211095, 0.42375049, 0.44016852],
       [0.19556367, 0.83945899, 0.26947657, 0.10512375, 0.59802791],
       [0.91556998, 0.09416882, 0.87463821, 0.25702766, 0.33094578]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [36]:
np.random.randn(2)

array([-0.56532305, -0.16907072])

In [37]:
np.random.randn(5,5)

array([[-0.38297605,  0.20391816,  0.71521736,  2.2854842 , -0.40096097],
       [-0.7573404 ,  0.58392903, -0.63269366,  0.01168207,  1.05745875],
       [ 0.60878432,  1.1784626 , -0.9534229 , -0.29072304, -2.89129321],
       [ 0.41643474, -0.97323354,  1.82921157,  0.21819047, -1.35527371],
       [ 0.0407772 ,  0.94339585,  0.25087589, -1.21514483, -0.15337191]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [38]:
np.random.randint(1,100)

11

In [39]:
np.random.randint(1,100,10)

array([43,  5, 36, 75, 40, 88, 49, 16, 11, 64])

## Reshape
Returns an array containing the same data with a new shape.

In [45]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [47]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [48]:
c = a - b
c

array([20, 29, 38, 47])

In [49]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [50]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [52]:
a < 35 # boolean array

array([ True,  True, False, False])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
a/a

In [ ]:
1/a

In [ ]:
arr**3

In [56]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B # element wise

array([[2, 0],
       [0, 4]])

In [54]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [55]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [59]:
rg = np.random.default_rng(1)

In [60]:
a = rg.random((2, 3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [61]:
a.sum()

3.290252281866131

In [62]:
a.min()

0.14415961271963373

In [63]:
a.max()

0.9504636963259353

In [65]:
a.argmax()

1

In [67]:
a.argmin()

2

In [69]:
a.sum(axis=0)     # sum of each column

array([1.46047107, 1.26229515, 0.56748606])

In [70]:
a.min(axis=1)     # min of each row

array([0.14415961, 0.31183145])

In [71]:
a.cumsum(axis=1)  # cumulative sum along each row

array([[0.51182162, 1.46228532, 1.60644493],
       [0.94864945, 1.2604809 , 1.68380735]])

In [76]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
ind

(0, 1)

In [77]:
a[ind]

0.9504636963259353

### Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [72]:
B = np.arange(3)
B

array([0, 1, 2])

In [73]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [74]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [75]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [ ]:
#Calcualting exponential (e^)
# np.exp(arr)

In [ ]:
np.max(arr) #same as arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

## Shape

Shape is an attribute that arrays have (not a method):

In [78]:
# Vector
arr.shape

(3, 3)

# Notice the two sets of brackets
arr.reshape(1,9) # row vector

In [80]:
arr.reshape(9,1) # column vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
arr.reshape(1,9).shape

(1, 9)

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [99]:
a

array([1, 2, 3])

In [101]:
# slice single item 
a[1]

2

In [120]:
#Creating sample array
arr = np.arange(0,11)

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr[4]

4

In [178]:
# slice items starting from index 
 
a = np.arange(10) 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
# slice items between indexes
arr[1:5]

array([1, 2, 3, 4])

In [106]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [117]:
# arr[:6:2] = 1000

In [180]:
# arr

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [122]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [123]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [125]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [126]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [127]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [128]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [130]:
arr_copy[:]=49

In [131]:
arr_copy

array([49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49])

In [132]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [133]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [134]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [135]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [136]:
# Getting individual element value
arr_2d[1,0]

20

In [137]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [138]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [139]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [140]:
#Set up matrix
arr2d = np.zeros((10,10))

In [146]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [147]:
#Length of array
arr_length = arr2d.shape[1]

In [148]:
arr_length

10

In [149]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [150]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [151]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [152]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [153]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [154]:
c.shape

(2, 2, 3)

In [155]:
c[1, ...]  # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [160]:
c[0, ...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [161]:
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [170]:
for element in b.flat:
    print(element)

0
1
2
3


In [169]:
b

array([0, 1, 2, 3])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
bool_arr = arr>4

In [5]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [6]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# del array 
del arr

## numpy.sort

Return a sorted copy of an array

parameter:--axis, kind (‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’), order(str or list of str)

In [9]:
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

In [10]:
np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

In [13]:
np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

In [14]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

In [15]:
a = np.array(values, dtype=dtype)       # create a structured array

In [16]:
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [17]:
np.sort(a, order='height') 

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [18]:
np.sort(a, order=['age', 'height'])  

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

## Sorting, searching, and counting

### numpy.lexsort
numpy.lexsort(keys, axis=- 1)
Perform an indirect stable sort using a sequence of keys

In [19]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')

In [20]:
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [22]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((a,b)) # Sort by a, then by b
ind

array([2, 4, 6, 5, 3, 1, 0], dtype=int64)

### numpy.argsort

numpy.argsort(a, axis=- 1, kind=None, order=None)

In [23]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [26]:
x = np.array([[0, 4], [4, 2]])
x

array([[0, 4],
       [4, 2]])

In [27]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind

array([[0, 1],
       [1, 0]], dtype=int64)

## “Automatic” Reshaping

To change the dimensions of an array, you can omit one of the sizes which will then be deduced automatically

In [28]:
a = np.arange(30)

In [31]:
a.shape

(30,)

In [38]:
b = a.reshape((3, -1, 2))  # -1 means "whatever is needed"
b.shape

(3, 5, 2)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])